require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe BoxesController do

  def mock_box(stubs={})
    @mock_box ||= mock_model(Box, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all boxes as @boxes" do
      Box.stub(:all) { [mock_box] }
      get :index
      assigns(:boxes).should eq([mock_box])
    end
  end

  describe "GET show" do
    it "assigns the requested box as @box" do
      Box.stub(:find).with("37") { mock_box }
      get :show, :id => "37"
      assigns(:box).should be(mock_box)
    end
  end

  describe "GET new" do
    it "assigns a new box as @box" do
      Box.stub(:new) { mock_box }
      get :new
      assigns(:box).should be(mock_box)
    end
  end

  describe "GET edit" do
    it "assigns the requested box as @box" do
      Box.stub(:find).with("37") { mock_box }
      get :edit, :id => "37"
      assigns(:box).should be(mock_box)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created box as @box" do
        Box.stub(:new).with({'these' => 'params'}) { mock_box(:save => true) }
        post :create, :box => {'these' => 'params'}
        assigns(:box).should be(mock_box)
      end

      it "redirects to the created box" do
        Box.stub(:new) { mock_box(:save => true) }
        post :create, :box => {}
        response.should redirect_to(box_url(mock_box))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved box as @box" do
        Box.stub(:new).with({'these' => 'params'}) { mock_box(:save => false) }
        post :create, :box => {'these' => 'params'}
        assigns(:box).should be(mock_box)
      end

      it "re-renders the 'new' template" do
        Box.stub(:new) { mock_box(:save => false) }
        post :create, :box => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested box" do
        Box.stub(:find).with("37") { mock_box }
        mock_box.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :box => {'these' => 'params'}
      end

      it "assigns the requested box as @box" do
        Box.stub(:find) { mock_box(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:box).should be(mock_box)
      end

      it "redirects to the box" do
        Box.stub(:find) { mock_box(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(box_url(mock_box))
      end
    end

    describe "with invalid params" do
      it "assigns the box as @box" do
        Box.stub(:find) { mock_box(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:box).should be(mock_box)
      end

      it "re-renders the 'edit' template" do
        Box.stub(:find) { mock_box(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested box" do
      Box.stub(:find).with("37") { mock_box }
      mock_box.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the boxes list" do
      Box.stub(:find) { mock_box }
      delete :destroy, :id => "1"
      response.should redirect_to(boxes_url)
    end
  end

end
